import { GameState, CharacterType, GamePhase, WorldState } from './types';

const BASE_WORLD: WorldState = {
  naziConsolidationLevel: 8,
  gamePhase: 'nazi_consolidation' as GamePhase,
  keyActorStates: {
    hitler: {
      name: 'Adolf Hitler',
      disposition: 'triumphant, moving to consolidate power rapidly',
      location: 'Reich Chancellery, Wilhelmstrasse',
      status: 'active',
      notes: 'Just appointed Chancellor. Planning to call new elections and neutralize opposition.',
    },
    hindenburg: {
      name: 'Paul von Hindenburg',
      disposition: 'reluctant, believes he has contained Hitler via cabinet constraints',
      location: 'Reichspräsident\'s Palace',
      status: 'active',
      notes: 'Old, frail, manipulated by Papen. Believes non-Nazi ministers will check Hitler.',
    },
    papen: {
      name: 'Franz von Papen',
      disposition: 'overconfident, believes he is the real power behind Hitler',
      location: 'Vice-Chancellery',
      status: 'active',
      notes: '"We have hired him." Fatally underestimates Nazi ruthlessness. Also Centre Party Catholic — potential lever.',
    },
    schleicher: {
      name: 'Kurt von Schleicher',
      disposition: 'bitter, plotting counter-moves',
      location: 'Berlin, private residence',
      status: 'active',
      notes: 'Former Chancellor. Potential ally against Hitler if approached carefully.',
    },
    goebbels: {
      name: 'Joseph Goebbels',
      disposition: 'ecstatic, organizing propaganda apparatus',
      location: 'NSDAP headquarters, Berlin',
      status: 'active',
      notes: 'Will control all media if Nazis consolidate. Key target to expose or isolate.',
    },
    spd_leadership: {
      name: 'SPD Leadership (Otto Wels et al.)',
      disposition: 'alarmed but committed to constitutional methods',
      location: 'SPD headquarters, Berlin',
      status: 'active',
      notes: 'Will eventually be the only party to vote against the Enabling Act.',
    },
    kpd_leadership: {
      name: 'KPD Leadership (Ernst Thälmann)',
      disposition: 'hostile to SPD, underestimating Nazi threat',
      location: 'KPD headquarters, Berlin',
      status: 'active',
      notes: 'Fatally calls SPD "social fascists." May be more receptive to united front arguments.',
    },
    reichswehr_command: {
      name: 'General Werner von Blomberg (Reichswehr)',
      disposition: 'accommodating to Hitler',
      location: 'Reichswehr HQ, Bendlerblock',
      status: 'active',
      notes: 'New Defense Minister, loyal to Hitler. Other generals may be more skeptical.',
    },
    centre_party: {
      name: 'Ludwig Kaas (Centre Party chairman)',
      disposition: 'deeply anxious, seeking guarantees from Hitler',
      location: 'Centre Party offices, Berlin',
      status: 'active',
      notes: 'Will ultimately lead Centre Party to vote for Enabling Act after extracting hollow promises. Key figure to persuade otherwise.',
    },
  },
  pendingEvents: [
    // ── Phase 1: Nazi Consolidation (Jan–Mar 1933) ───────────────────────────
    {
      id: 'protection_decree',
      description: 'Hitler invokes Article 48 to issue the Decree for the Protection of the German People, banning opposition press and meetings.',
      triggerCondition: 'historical',
      scheduledDate: '1933-02-04T00:00:00',
      triggered: false,
      naziConsolidationEffect: 6,
      preventable: false,
      keyActors: ['Hitler', 'Frick'],
      historicalNote: 'Decree issued 4 February 1933, five days after appointment.',
    },
    {
      id: 'reichstag_dissolved',
      description: 'Hitler dissolves the Reichstag and calls new elections for March 5, 1933.',
      triggerCondition: 'historical',
      scheduledDate: '1933-02-01T00:00:00',
      triggered: false,
      naziConsolidationEffect: 4,
      preventable: false,
      keyActors: ['Hitler', 'Hindenburg'],
      historicalNote: 'Dissolution announced 1 February 1933.',
    },
    {
      id: 'reichstag_fire',
      description: 'The Reichstag building burns. Marinus van der Lubbe is arrested. The Nazis immediately blame a Communist conspiracy.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1933-02-27T21:00:00',
      triggered: false,
      naziConsolidationEffect: 18,
      preventable: true,
      keyActors: ['Marinus van der Lubbe', 'Göring', 'Goebbels'],
      historicalNote: 'Fire began 21:14 on 27 February 1933. SA involvement long suspected but never proven.',
    },
    {
      id: 'fire_decree',
      description: 'The Reichstag Fire Decree suspends all civil liberties and enables mass arrests of Communists, SPD activists, and journalists.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1933-02-28T00:00:00',
      triggered: false,
      naziConsolidationEffect: 20,
      preventable: true,
      keyActors: ['Hitler', 'Hindenburg', 'Frick'],
      historicalNote: 'Signed the morning after the fire. Legal basis for ~10,000 arrests.',
    },
    {
      id: 'march_elections',
      description: 'Reichstag elections held under a climate of terror; NSDAP wins 43.9% but falls short of majority.',
      triggerCondition: 'historical',
      scheduledDate: '1933-03-05T00:00:00',
      triggered: false,
      naziConsolidationEffect: 8,
      preventable: false,
      keyActors: ['Hitler', 'Goebbels', 'SPD', 'Centre Party'],
      historicalNote: '5 March 1933. Despite terror, NSDAP did not win outright majority.',
    },
    {
      id: 'enabling_act_vote',
      description: 'Reichstag votes on the Enabling Act at the Kroll Opera House, surrounded by SA and SS. Passes 444–94 (SPD only opposition; KPD deputies already arrested).',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1933-03-23T00:00:00',
      triggered: false,
      naziConsolidationEffect: 25,
      preventable: true,
      keyActors: ['Hitler', 'Otto Wels', 'Ludwig Kaas', 'Centre Party deputies'],
      historicalNote: 'Passed 23 March 1933. Centre Party voted yes after hollow Nazi promises.',
    },
    // ── Phase 2: Weimar Collapse (Mar 1933–Aug 1934) ─────────────────────────
    {
      id: 'dachau_opens',
      description: 'Himmler opens Dachau concentration camp, the first permanent Nazi camp, to hold political prisoners.',
      triggerCondition: 'historical',
      scheduledDate: '1933-03-22T00:00:00',
      triggered: false,
      naziConsolidationEffect: 8,
      preventable: false,
      keyActors: ['Himmler', 'Göring'],
      historicalNote: 'Opened 22 March 1933 near Munich.',
    },
    {
      id: 'jewish_boycott',
      description: 'The Nazi regime organises a nationwide boycott of Jewish businesses, signaling the beginning of systematic antisemitic persecution.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1933-04-01T00:00:00',
      triggered: false,
      naziConsolidationEffect: 5,
      preventable: true,
      keyActors: ['Goebbels', 'Streicher'],
      historicalNote: '1 April 1933 boycott organised by SA under Goebbels direction.',
    },
    {
      id: 'parties_banned',
      description: 'All political parties except the NSDAP are banned or dissolved; Germany becomes a one-party state.',
      triggerCondition: 'historical',
      scheduledDate: '1933-07-14T00:00:00',
      triggered: false,
      naziConsolidationEffect: 12,
      preventable: false,
      keyActors: ['Hitler', 'Frick'],
      historicalNote: 'Law Against the Formation of New Parties, 14 July 1933.',
    },
    {
      id: 'night_of_long_knives',
      description: 'Hitler purges the SA leadership and conservative critics. Ernst Röhm, Schleicher, and dozens of others are murdered over three days.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1934-06-30T00:00:00',
      triggered: false,
      naziConsolidationEffect: 15,
      preventable: true,
      keyActors: ['Hitler', 'Himmler', 'Göring', 'Ernst Röhm', 'Kurt von Schleicher'],
      historicalNote: '30 June – 2 July 1934. At least 85 killed. Schleicher and his wife shot at home.',
    },
    {
      id: 'hindenburg_death',
      description: 'President Hindenburg dies. Hitler merges the offices of Chancellor and President; German military swears personal oath to Hitler.',
      triggerCondition: 'historical',
      scheduledDate: '1934-08-02T00:00:00',
      triggered: false,
      naziConsolidationEffect: 15,
      preventable: false,
      keyActors: ['Hindenburg', 'Hitler', 'Blomberg'],
      historicalNote: '2 August 1934. Wehrmacht oath to Hitler personally taken the same day.',
    },
    // ── Phase 3: Third Reich (Aug 1934–Sep 1939) ──────────────────────────────
    {
      id: 'nuremberg_laws',
      description: 'The Nuremberg Laws strip German Jews of citizenship and ban marriage between Jews and non-Jews.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1935-09-15T00:00:00',
      triggered: false,
      naziConsolidationEffect: 10,
      preventable: true,
      keyActors: ['Hitler', 'Frick', 'Streicher'],
      historicalNote: 'Reich Citizenship Law and Law for Protection of German Blood, 15 September 1935.',
    },
    {
      id: 'rhineland_remilitarisation',
      description: 'German troops reoccupy the demilitarised Rhineland, violating Versailles and Locarno. France and Britain do not respond militarily.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1936-03-07T00:00:00',
      triggered: false,
      naziConsolidationEffect: 12,
      preventable: true,
      keyActors: ['Hitler', 'Blomberg', 'British Cabinet', 'French Government'],
      historicalNote: '7 March 1936. Hitler later said this was his greatest gamble; French action would have ended his regime.',
    },
    {
      id: 'anschluss',
      description: 'Germany annexes Austria. Austrian Nazis invite German troops; Schuschnigg resigns. Britain and France accept the fait accompli.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1938-03-12T00:00:00',
      triggered: false,
      naziConsolidationEffect: 14,
      preventable: true,
      keyActors: ['Hitler', 'Schuschnigg', 'Seyss-Inquart', 'Chamberlain', 'Daladier'],
      historicalNote: '12 March 1938. Schuschnigg had called a referendum; Hitler forced its cancellation.',
    },
    {
      id: 'munich_agreement',
      description: 'Britain, France, Italy, and Germany sign the Munich Agreement, ceding the Sudetenland to Germany. Chamberlain declares "peace for our time."',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1938-09-30T00:00:00',
      triggered: false,
      naziConsolidationEffect: 16,
      preventable: true,
      keyActors: ['Chamberlain', 'Daladier', 'Hitler', 'Mussolini', 'Beneš'],
      historicalNote: '30 September 1938. Czechoslovakia was not represented at the conference.',
    },
    {
      id: 'kristallnacht',
      description: 'Nationwide pogrom: synagogues burned, Jewish businesses destroyed, ~30,000 Jewish men arrested and sent to concentration camps.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1938-11-09T00:00:00',
      triggered: false,
      naziConsolidationEffect: 10,
      preventable: true,
      keyActors: ['Goebbels', 'Himmler', 'SA', 'SS'],
      historicalNote: '9–10 November 1938. Triggered by assassination of diplomat Ernst vom Rath by Herschel Grynszpan.',
    },
    // ── Phase 4: Wartime (Sep 1939–May 1945) ─────────────────────────────────
    {
      id: 'invasion_poland',
      description: 'Germany invades Poland. Britain and France declare war two days later. World War II begins.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1939-09-01T04:45:00',
      triggered: false,
      naziConsolidationEffect: 5,
      preventable: true,
      keyActors: ['Hitler', 'Chamberlain', 'Daladier', 'Beck', 'Polish Government'],
      historicalNote: '1 September 1939. Britain and France declared war 3 September 1939.',
    },
    {
      id: 'fall_of_france',
      description: 'Germany defeats France in six weeks. France signs armistice; Vichy regime established. Britain stands alone.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1940-06-22T00:00:00',
      triggered: false,
      naziConsolidationEffect: 15,
      preventable: true,
      keyActors: ['Hitler', 'de Gaulle', 'Weygand', 'Pétain', 'Churchill'],
      historicalNote: 'France signed armistice 22 June 1940 in the same railway carriage as 1918.',
    },
    {
      id: 'wannsee_conference',
      description: 'Senior Nazi officials coordinate the "Final Solution to the Jewish Question" — systematic genocide of all European Jews.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1942-01-20T00:00:00',
      triggered: false,
      naziConsolidationEffect: 0,
      preventable: true,
      keyActors: ['Heydrich', 'Eichmann', 'Himmler'],
      historicalNote: '20 January 1942 at Wannsee villa, Berlin. Protocol survives as historical document.',
    },
    {
      id: 'stalingrad',
      description: 'German 6th Army surrenders at Stalingrad. ~800,000 Axis casualties. The tide of the Eastern Front turns decisively.',
      triggerCondition: 'historical',
      scheduledDate: '1943-02-02T00:00:00',
      triggered: false,
      naziConsolidationEffect: -10,
      preventable: false,
      keyActors: ['Paulus', 'Chuikov', 'Zhukov', 'Hitler'],
      historicalNote: 'Paulus surrendered 2 February 1943. Hitler had forbidden retreat.',
    },
    {
      id: 'july_20_plot',
      description: 'Claus von Stauffenberg plants a bomb at Hitler\'s Wolf\'s Lair headquarters. Hitler survives the blast. The conspirators are arrested and executed.',
      triggerCondition: 'historical_unless_prevented',
      scheduledDate: '1944-07-20T12:42:00',
      triggered: false,
      naziConsolidationEffect: 8,
      preventable: true,
      keyActors: ['Stauffenberg', 'Beck', 'Goerdeler', 'Rommel', 'Canaris'],
      historicalNote: '20 July 1944. Bomb moved behind table leg; Hitler survived. 4,980 people executed in aftermath.',
    },
    {
      id: 've_day',
      description: 'Germany surrenders unconditionally. Hitler is dead. The Third Reich ends after twelve years.',
      triggerCondition: 'historical',
      scheduledDate: '1945-05-08T00:00:00',
      triggered: false,
      naziConsolidationEffect: -100,
      preventable: false,
      keyActors: ['Dönitz', 'Keitel', 'Eisenhower', 'Zhukov'],
      historicalNote: 'V-E Day 8 May 1945. Unconditional surrender signed at Reims (7 May) and Berlin (8 May).',
    },
  ],
  triggeredEvents: [],
  causalChain: [
    'Jan 30: Hitler appointed Reich Chancellor by Hindenburg',
  ],
  reichstagFireStatus: 'not_happened',
  enablingActStatus: 'not_introduced',
  extraDetails: {
    electionsCalled: false,
    pressRestrictions: false,
    saStreetViolence: 'low',
    internationalAwareness: 'low',
    centrepartyPosition: 'undecided',
    britishGovernmentAwareness: 'dismissive',
  },
};

function createJournalistState(): GameState {
  return {
    version: 1,
    gameStatus: 'playing',
    currentDateTime: 'Monday, January 30, 1933, 9:00 AM',
    currentDateISO: '1933-01-30T09:00:00',
    turnCount: 0,
    currentLocation: 'Café Josty, Potsdamer Platz, Berlin',
    player: {
      name: 'Karl Brandt',
      occupation: 'Journalist',
      affiliation: 'Berliner Tageblatt',
      physicalStatus: 'healthy',
      money: 12,
      inventory: [
        'press identification card',
        'reporter\'s notebook',
        'fountain pen',
        'street map of Berlin',
        'Berliner Tageblatt press badge',
      ],
      relationships: [
        {
          person: 'Theodor Wolff (editor-in-chief, Berliner Tageblatt)',
          status: 'acquaintance',
          lastContact: '1933-01-28',
          notes: 'Skeptical of Nazi rise but fears reprisals. Wants compelling evidence before printing anything inflammatory.',
        },
        {
          person: 'Hans Schreiber (SPD Reichstag deputy)',
          status: 'acquaintance',
          lastContact: '1933-01-15',
          notes: 'Met at a parliamentary press event. Cautiously sympathetic to liberal press.',
        },
        {
          person: 'Greta Fuchs (café regular, secretary at Interior Ministry)',
          status: 'acquaintance',
          lastContact: '1933-01-29',
          notes: 'Shares a table at Café Josty most mornings. Nervous about the political climate.',
        },
      ],
      knownFacts: [
        'Hitler was appointed Reich Chancellor by Hindenburg this morning, January 30, 1933.',
        'Papen is Vice-Chancellor and believes he can control Hitler.',
        'The Reichstag is scheduled to meet but may be dissolved for new elections.',
        'The KPD (Communist Party) is legal but under increasing pressure.',
        'The SA (Brownshirts) held a torchlight parade through Berlin last night.',
        'Schleicher was forced out as Chancellor after Papen undermined him with Hindenburg.',
        'The Enabling Act, if passed, would give Hitler dictatorial power for four years.',
        'The Reichstag Fire Decree could suspend civil liberties if an emergency is declared.',
      ],
      characterType: 'journalist',
    },
    world: BASE_WORLD,
    journal: [],
  };
}

function createCentrePartyState(): GameState {
  return {
    version: 1,
    gameStatus: 'playing',
    currentDateTime: 'Monday, January 30, 1933, 10:30 AM',
    currentDateISO: '1933-01-30T10:30:00',
    turnCount: 0,
    currentLocation: 'Centre Party offices, Linkstrasse, Berlin',
    player: {
      name: 'Heinrich Möller',
      occupation: 'Reichstag Deputy',
      affiliation: 'Zentrumspartei (Centre Party)',
      physicalStatus: 'healthy',
      money: 45,
      inventory: [
        'Reichstag member pass',
        'Centre Party membership card',
        'leather briefcase',
        'telephone directory (Berlin)',
        'draft letter to Cardinal Bertram',
      ],
      relationships: [
        {
          person: 'Ludwig Kaas (Centre Party chairman)',
          status: 'acquaintance',
          lastContact: '1933-01-28',
          notes: 'Party chairman. Deeply anxious, meeting with Hitler to extract guarantees. Believes he can negotiate. Dangerously naive.',
        },
        {
          person: 'Monsignor Georg Schreiber (Centre Party deputy, Münster)',
          status: 'trusted',
          lastContact: '1933-01-30',
          notes: 'Close colleague. Shares your doubts about accommodating the Nazis. Catholic conscience guides him.',
        },
        {
          person: 'Franz von Papen (Vice-Chancellor)',
          status: 'acquaintance',
          lastContact: '1933-01-20',
          notes: 'Fellow Catholic but has abandoned the Centre Party. Arrogantly certain he controls Hitler. Might be leverage or a bridge.',
        },
        {
          person: 'Otto Wels (SPD chairman)',
          status: 'stranger',
          lastContact: null,
          notes: 'SPD leader. Would need careful approach — Centre Party and SPD have clashed badly. But they share opposition to the Enabling Act.',
        },
      ],
      knownFacts: [
        'Hitler was appointed Chancellor this morning. Hindenburg signed the appointment.',
        'The Enabling Act will require a 2/3 majority in the Reichstag. Without Centre Party votes, it cannot pass.',
        'Centre Party has 74 seats. NSDAP + DNVP together cannot reach 2/3 without us.',
        'Chairman Kaas is already seeking a private meeting with Hitler to extract constitutional guarantees.',
        'The Vatican is watching carefully — a Concordat with the new government is being discussed.',
        'Papen gave Hitler our votes in exchange for a promise to protect Catholic institutions.',
        'The SPD will vote no. The KPD deputies will likely be arrested before the vote.',
        'If our party votes yes, the Enabling Act passes. If we vote no, it fails.',
        'Nazi SA men have already begun intimidating deputies in the streets.',
        'The vote is expected around late March — we have weeks to organize resistance or capitulation.',
      ],
      characterType: 'centre_party_deputy',
    },
    world: {
      ...BASE_WORLD,
      extraDetails: {
        ...BASE_WORLD.extraDetails,
        centrepartyPosition: 'negotiating',
        concordatNegotiations: 'rumored',
        saIntimidation: 'beginning',
      },
    },
    journal: [],
  };
}

function createChamberlainState(): GameState {
  return {
    version: 1,
    gameStatus: 'playing',
    currentDateTime: 'Monday, January 30, 1933, 10:00 AM',
    currentDateISO: '1933-01-30T10:00:00',
    turnCount: 0,
    currentLocation: '11 Downing Street, London',
    player: {
      name: 'Neville Chamberlain',
      occupation: 'Chancellor of the Exchequer',
      affiliation: 'His Majesty\'s Government (Conservative)',
      physicalStatus: 'healthy',
      money: 0,
      inventory: [
        'Cabinet briefing papers',
        'Foreign Office telegram: Hitler appointed Chancellor',
        'Treasury red box',
        'personal appointment diary',
        'telephone (direct line to Foreign Office)',
      ],
      relationships: [
        {
          person: 'Sir John Simon (Foreign Secretary)',
          status: 'acquaintance',
          lastContact: '1933-01-27',
          notes: 'Foreign Secretary. Cautious, legalistic, deeply reluctant to make waves. Must be convinced that Germany is an urgent threat.',
        },
        {
          person: 'Ramsay MacDonald (Prime Minister)',
          status: 'acquaintance',
          lastContact: '1933-01-25',
          notes: 'National Government PM, increasingly frail and distracted. Dislikes confrontation with any foreign power.',
        },
        {
          person: 'Ambassador Horace Rumbold (Berlin)',
          status: 'acquaintance',
          lastContact: '1933-01-20',
          notes: 'British Ambassador in Berlin. Astute observer — his dispatches have been increasingly alarming. A key source of intelligence.',
        },
        {
          person: 'Édouard Daladier (French War Minister)',
          status: 'stranger',
          lastContact: null,
          notes: 'French government contact. France is more alarmed by Hitler than Britain. Could be an ally in raising international pressure.',
        },
        {
          person: 'The Times (Geoffrey Dawson, editor)',
          status: 'acquaintance',
          lastContact: '1933-01-10',
          notes: 'Editor of The Times. Influential but instinctively pro-appeasement. Can be briefed but will need strong evidence to change editorial line.',
        },
      ],
      knownFacts: [
        'Hitler appointed German Chancellor this morning. Foreign Office telegram arrived at 9AM.',
        'Hitler has been Chancellor of the Exchequer\'s main concern since NSDAP\'s September 1930 electoral surge.',
        'Britain\'s official position is non-interference in German domestic politics.',
        'France views Germany with far greater alarm — they share a border.',
        'The League of Nations is theoretically the mechanism for international pressure, but it is weak.',
        'German rearmament, if Hitler pursues it, would violate the Treaty of Versailles.',
        'British banks have significant loans to German industry — economic leverage exists.',
        'Ambassador Rumbold has been sending increasingly alarmed dispatches from Berlin.',
        'The Enabling Act vote is expected in late March — international pressure before then could matter.',
        'The British press is largely dismissive of Hitler, treating him as a temporary phenomenon.',
      ],
      characterType: 'chamberlain',
    },
    world: {
      ...BASE_WORLD,
      extraDetails: {
        ...BASE_WORLD.extraDetails,
        britishGovernmentAwareness: 'dismissive',
        frenchGovernmentAwareness: 'alarmed',
        leagueOfNationsInvolvement: 'none',
        internationalPressure: 'none',
        britishBankExposure: 'high',
      },
    },
    journal: [],
  };
}

export function createInitialState(characterType: CharacterType = 'journalist'): GameState {
  switch (characterType) {
    case 'centre_party_deputy':
      return createCentrePartyState();
    case 'chamberlain':
      return createChamberlainState();
    default:
      return createJournalistState();
  }
}
